/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_paquete_rpc (XDR *xdrs, paquete_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_value_args (XDR *xdrs, set_value_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->v_value2.v_value2_val, (u_int *) &objp->v_value2.v_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_value_res (XDR *xdrs, get_value_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->v_value2.v_value2_val, (u_int *) &objp->v_value2.v_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
